var radioObjs = [
    new RadioStation("KissFM", "http://80.86.106.143:9128/kissfm.aacp", ""), 
    new RadioStation("Radio Zu", "http://live.romanticfm.ro:9123/radiozu.aacp", ""), 
    new RadioStation("Guerilla", "http://live.guerrillaradio.ro:8010/guerrilla.aac", ""), 
    new RadioStation("ProFM", "http://stream.profm.ro:8012/profm.mp3", ""), 
    new RadioStation("Rock FM", "http://live.rockfm.ro:9128/rockfm.aacp", ""), 
    new RadioStation("Europa FM", "http://astreaming.europafm.ro:8000/europafm_mp3_64k ", ""), 
    new RadioStation("Virgin Radio", "http://astreaming.virginradio.ro:8000/virgin_aacp_64k", ""), 
    new RadioStation("Alt Radio", "http://asculta.altradio.ro:8557", ""), 
    new RadioStation("Radio Cafe", "http://live.radiocafe.ro:8064/", ""), 
    new RadioStation("Magic FM", "http://live.magicfm.ro:9128/magicfm.aacp", ""), 
    new RadioStation("One FM", "http://live.onefm.ro:9128/onefm.aacp", ""), 
    new RadioStation("Crazy Radio", "http://live.crazyradio.ro:8024/stream", ""), 
    new RadioStation("Digi FM", "http://edge76.rdsnet.ro:84/digifm/digifm.mp3", ""), 
    new RadioStation("Go FM", "http://live.gofm.ro:9128/", ""), 
    new RadioStation("Radio Zuper", "http://live.radiozuper.ro:8080/stream/1/", ""), 
    new RadioStation("Vibe FM", "http://89.37.58.102:8000/vibefm_mp3_64k", ""), 
    new RadioStation("Happy FM", "http://live.happyfm.ro:8585", ""),  
]
